---
driver:
  name: docker

provisioner:
  name: chef_zero_encrypt_databags
  data_bags_path: spec/fixtures/data_bags
  encrypted_data_bag_secret_key_path: spec/fixtures/encrypted_data_bag_secret

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    attributes: {}
    run_list: fake::default
