AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Metrics/LineLength:
  Max: 90

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: always

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
