AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Metrics/LineLength:
  Max: 90

Style/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: always

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
