---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout

      - type: cache-restore
        key: bundler-{{ checksum "Gemfile.lock" }}

      - run: gem install bundler --pre
      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: bundler-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rubocop
      - run: bundle exec rspec
